# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:
  - r: release
    after_success: Rscript -e 'covr::coveralls()'
    before_deploy: Rscript -e 'remotes::install_cran("pkgdown", "tidyverse")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true

