# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
  - os: osx
  - r: devel
  - r: release
    after_success: Rscript -e 'covr::coveralls()'
    before_deploy:
    - Rscript -e 'remotes::install_cran("pkgdown")'
    - Rscript -e 'remotes::install_github("maurolepore/pkgdoc")'
    - Rscript -e 'install.packages(c("tidyverse", "ggstance", "lvplot"))'
    - Rscript -e 'install.packages(c("ggbeeswarm", "modelr", "kableExtra", "DT"))'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
  - r: oldrel
  - r: 3.3
  - r: 3.2
  allow_failures:
  - os: osx
  - r: 3.2

