To help you analyze forest diversity and dynamics with ForestGEO data we developed [__fgeo__](https://forestgeo.github.io/fgeo/). _[__fgeo__] is a collection of R packages that share an underlying design philosophy, grammar, and data structures, with the aim that learning one package makes it easier to learn the next. As well as being a collection of packages, [__fgeo__] itself is also a package. This provides a convenient way of downloading all [__fgeo__] packages with [`install.packages("fgeo")`]_, and of leading them with `library(fgeo)`. 

This first release of __fgeo__ conservatively provides only the [most obviously needed tools](https://forestgeo.github.io/fgeo/articles/siteonly/reference.html), including functions to access example datasets ([`fgeo.x::download_data()`](https://forestgeo.github.io/fgeo.x/reference/download_data)); to pick specific rows ([`fgeo.tool::pick_main_stem()`](https://forestgeo.github.io/fgeo.tool/reference/pick_main_stem)) and add useful columns ([`fgeo.tool::add_quad()`](https://forestgeo.github.io/fgeo.tool/reference/add_var)); to plot species distribution and topography ([`fgeo.plot::autoplot()`](https://forestgeo.github.io/fgeo.plot/reference/autoplot.sp_elev)); to analyze abundance and basal area ([`fgeo.analyze::abundance()`](https://forestgeo.github.io/fgeo.analyze/reference/abundance)), demography ([`fgeo.analyze::mortality_ctfs()`](https://forestgeo.github.io/fgeo.analyze/reference/recruitment_ctfs)), and species-habitat association ([`fgeo.analyze::tt_test()`](https://forestgeo.github.io/fgeo.analyze/reference/tt_test)).

### How __fgeo__ compares to other projects.

__fgeo__ follows the design principles and style of the __tidyverse__ (https://tidyverse.org), the most popular, coherent ecosystem of R packages today.

__fgeo__ is not a new version of the "[CTFS R Package](http://ctfs.si.edu/Public/CTFSRPackage/)" but a modern reimagination. Notably, the number of features of __fgeo__ is much smaller. It aims not for quantity but for correctness, maintenance, coherence, ease of use, and relevance.
