---
title: "Get started"
author: "Mauro Lepore"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Get started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  eval = TRUE,
  collapse = TRUE,
  comment = "#>"
)

library(dplyr)
```

## Overview

__fgeo__ provides a wide range of tools to analyse forest diversity and dynamics. It installs and loads multiple R packages, functions, and datasets in a single step. (To learn more about the structure of ForestgGEO's software see [this article](https://goo.gl/c5X6qk).)

## Functions

```{r, echo=FALSE}
fgeo::fgeo_index_functions() %>% 
  # Make clickable links
  dplyr::mutate(
    fun = fgeo::fgeo_link(package, fun),
    package = fgeo::fgeo_link(package)
  ) %>% 
  DT::datatable(escape = FALSE)
  # knitr::kable()
```

## Datasets

```{r, echo=FALSE}
fgeo::fgeo_index_datasets() %>% 
  # Make clickable links
  dplyr::mutate(
    dataset = fgeo::fgeo_link(package, dataset),
    package = fgeo::fgeo_link(package)
  ) %>% 
  DT::datatable(escape = FALSE)
  # knitr::kable()
```


## Get Started

To get started run this:

```{r}
# install.packages("remotes")
# remotes::install_github("fgeo")
library(fgeo)
```

(See [installation](https://forestgeo.github.io/fgeo/#installation).)
