---
title: "Reference"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Quick Search}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message=FALSE, 
  warning=FALSE,
  collapse = TRUE,
  comment = "#>"
)

library(fgeo)
library(tidyverse)
```

```{r}
has_concept <- function(string) {
  fgeo:::search_help() %>% 
    family_contains(string) %>% 
    collapse_alias() %>% 
    # TODO: Add param link
    link() %>% 
    dplyr::select(package, topic, alias, title)
}

family_contains <- function(entries, string) {
  dplyr::filter(entries, concept %in% string)
}

collapse_alias <- function(entries) {
  entries %>% 
    dplyr::group_by(topic) %>% 
    dplyr::mutate(name = paste0(unique(alias), collapse = ", ")) %>% 
    dplyr::ungroup()
}

link <- function(x) {
  x %>% 
    dplyr::mutate(
      topic = glue::glue_data(
        ., 
        "<a href=https://forestgeo.github.io/\\
        {package}/reference/{topic}>{topic}</a>"
      ),
      package = glue::glue_data(
        ., 
        "<a href=https://forestgeo.github.io/\\
        {package}>{package}</a>"
      )
    ) %>% 
    dplyr::arrange(package)
}

link_pkg <- function(x) {
  glue::glue("<a href=https://forestgeo.github.io/{package}>{package}</a>")
}

datatable_n <- function(x, n = nrow(x)) {
  DT::datatable(x, escape = FALSE, options = list(pageLength = n))
}
```

### Explore fgeo

```{r}
datatable_n(has_concept("functions to explore fgeo"))
```

### Abundance

```{r}
datatable_n(has_concept("functions for abundance and basal area"))
```

### Demography

```{r}
datatable_n(has_concept("demography functions"))
```

### Habitat

```{r}
datatable_n(has_concept("habitat functions"))
```

### Datasets

```{r}
datatable_n(has_concept("datasets"))
```


