---
title: "Reference"
output: html_vignette
vignette: >
  %\VignetteIndexEntry{Quick Search}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(dplyr)
library(fgeo)
library(pkgdoc)
```

```{r, warning=FALSE}

url_fgeo <- "https://forestgeo.github.io/"

fgeo_reference_concept <- function(x) {
  reference_concept(x, url = url_fgeo, packages = fgeo:::fgeo_packages()) %>% 
    custom_table()
}

fgeo_reference_package <- function(x) {
  reference_package(x, url = url_fgeo, packages = fgeo:::fgeo_packages()) %>% 
    custom_table()
}

custom_table <- function(x) {
  x %>% 
    select(-package, -concept) %>% 
    unique() %>%
    knitr::kable(
      x, 
      format = "html",
      col.names = NULL,
      escape = FALSE
    ) %>%
    kableExtra::column_spec(1, bold = TRUE) %>% 
    kableExtra::column_spec(2, width = "20em")
}
```

Search globally in the search box below, or navigate the index clicking the menu on the right.

### Global search

```{r, warning=FALSE}
fgeo:::fgeo_packages() %>% 
  purrr::map_dfr(reference_package, url = url_fgeo) %>% 
  select(-package, -concept) %>% 
  unique() %>% 
  purrr::set_names(c("", "object", "description")) %>% 
  DT::datatable(
    escape = FALSE,
    rownames = NULL,
    options = list(
      # f: filter, t: table, i: information
      dom = "fti",
      search = list(search = "topography")
    )
  )
```

### Explore fgeo

```{r}
fgeo_reference_concept("functions to explore fgeo")
```

### Plot

```{r}
fgeo_reference_concept("plot functions")
```

### Abundance

```{r}
fgeo_reference_concept("functions for abundance and basal area")
```

### Demography

```{r}
fgeo_reference_concept("demography functions") 
```

### Habitat

```{r}
fgeo_reference_concept("habitat functions")
```

### Miscellaneous tools

#### Import ForestGEO data

```{r}
fgeo_reference_concept("functions to import ForestGEO data")
```

#### Edit data in place

```{r}
fgeo_reference_concept(c(
  "functions to edit ForestGEO data in place",
  "general functions to edit data in place"
))
```

#### Pick/drop rows with matching conditions 

```{r}
fgeo_reference_concept(c(
  "general functions to pick or drop rows of a dataframe",
  "functions to pick or drop rows of a ForestGEO dataframe"
))
```

#### Add new columns to a dataframe

```{r}
fgeo_reference_concept("functions to add columns to dataframes")
```

### Datasets

```{r}
fgeo_reference_concept("datasets")
```
